version: '3'
services:
  nginx:
    build: conf/nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/workdir
      - ./conf/nginx/conf/site.conf:/etc/nginx/conf.d/sit.conf
      - ./conf/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
      - db
  db:
    image: mysql:5.7
    environment:
      #Infos de connexion à la bdd dans le fichier connect.php
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits
    volumes:
      - ./database/:/docker-entrypoint-initdb.d

  php:
    build: .
    links:
      - db
    volumes:
      - ./www:/workdir
    ports:
      - "8080:80"